### ISSUE TITLE
Doesn't work on firefox to firefox

### ISSUE THREAD

**Issue by sojharo** [mgechev/angular-webrtc#1]
Hi,

This is not working when two peers are on Firefox. However, Firefox to chrome worked but video stream was not transferred between peers. Audio got transferred.

Any idea what could possibly be wrong. Firefox is using multistream feature which is under development in chrome. It seems the reason of the error. Have a look please:

https://hacks.mozilla.org/2015/03/webrtc-in-firefox-38-multistream-and-renegotiation/

https://code.google.com/p/chromium/issues/detail?id=465349

**Comment by mgechev** [comment]
I'll take a look next couple of days, thanks for pointing this out!

**Comment by sojharo** [comment]
Sorry, the above links are only suitable for my use case. I am adding multiple streams I have debugged the issue of firefox and if you allow I would give make a pull request. The real issue is of setRemoteDescription(). Firefox assumes all the arguments supplied.

**Comment by mgechev** [comment]
Just merged the PR. Thanks for the fix!
